name: 'Desplegar Infraestructura de Azure (Terraform)'

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  terraform:
    name: 'Aplicar Terraform'
    runs-on: ubuntu-latest
    
    # Establece el directorio de trabajo para todos los comandos 'run' de este job.
    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout del código del repositorio
      uses: actions/checkout@v4

    - name: Iniciar sesión en Azure
      uses: azure/login@v1
      with:
        
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Instalar y configurar terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.2.9 

    - name: Terraform Init
      run: terraform init
      

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Guardar outputs de Terraform en un archivo JSON
      run: terraform output -json > terraform-outputs.json

    - name: Subir artefacto con los outputs para el siguiente Job
      uses: actions/upload-artifact@v4
      with:
        name: terraform-outputs
        # ¡Importante! La ruta ahora debe incluir la carpeta 'infra'
        path: infra/terraform-outputs.json